### ISSUE TITLE
SOTA claims

### ISSUE THREAD

**Issue by xl-sr** [BlingHe/PixelFolder#1]
Hi,

you write PixelFolder achieves new state-of-the-art on LSUN church and FFHQ. It seems that you're not aware of all previous approaches, see references below

https://paperswithcode.com/sota/image-generation-on-lsun-churches-256-x-256
https://paperswithcode.com/sota/image-generation-on-ffhq-256-x-256

**Comment by BlingHe** [comment]
Thanks for this comment, and we will revise our statement in our new version.
